// Theme toggle and mobile nav
const themeToggle = document.getElementById('themeToggle');
const navToggle = document.getElementById('navToggle');
const navList = document.getElementById('navList');

themeToggle && themeToggle.addEventListener('click', ()=>{
  const current = document.documentElement.getAttribute('data-theme');
  if(current === 'light'){
    document.documentElement.removeAttribute('data-theme');
    themeToggle.textContent = '🌙';
  } else {
    document.documentElement.setAttribute('data-theme','light');
    themeToggle.textContent = '☀️';
  }
});

navToggle && navToggle.addEventListener('click', ()=>{
  if(navList.style.display === 'flex') navList.style.display = 'none';
  else navList.style.display = 'flex';
});

// Smooth scrolling for internal links
document.querySelectorAll('a[href^="#"]').forEach(a=>{
  a.addEventListener('click', e=>{
    const href = a.getAttribute('href');
    if(href.length>1){
      e.preventDefault();
      document.querySelector(href).scrollIntoView({behavior:'smooth'});
      if(window.innerWidth<=880) navList.style.display='none';
    }
  })
});

const artCanvas = document.getElementById('generatedArt');
if(artCanvas && artCanvas.getContext){
  const ctx = artCanvas.getContext('2d');
  const width = artCanvas.width;
  const height = artCanvas.height;

  const bg = ctx.createLinearGradient(0, 0, width, height);
  bg.addColorStop(0, '#1a2754');
  bg.addColorStop(0.5, '#3e6dff');
  bg.addColorStop(1, '#8d42ff');
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  const drawBlob = (x, y, radius, color) => {
    ctx.save();
    ctx.fillStyle = color;
    ctx.globalAlpha = 0.82;
    ctx.beginPath();
    ctx.ellipse(x, y, radius * 1.5, radius, Math.PI / 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
  };

  drawBlob(width * 0.25, height * 0.4, 80, '#ff8a6f');
  drawBlob(width * 0.6, height * 0.3, 60, '#6bceff');
  drawBlob(width * 0.7, height * 0.7, 100, '#f9c74f');
  drawBlob(width * 0.35, height * 0.75, 70, '#c86dff');

  ctx.strokeStyle = 'rgba(255,255,255,0.28)';
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(width * 0.05, height * 0.2);
  ctx.lineTo(width * 0.4, height * 0.1);
  ctx.lineTo(width * 0.9, height * 0.2);
  ctx.stroke();

  ctx.beginPath();
  ctx.arc(width * 0.82, height * 0.65, 34, 0, Math.PI * 2);
  ctx.stroke();

  for(let i = 0; i < 24; i++){
    const x = Math.random() * width;
    const y = Math.random() * height;
    const size = Math.random() * 3 + 1.5;
    ctx.fillStyle = 'rgba(255,255,255,0.65)';
    ctx.beginPath();
    ctx.arc(x, y, size, 0, Math.PI * 2);
    ctx.fill();
  }

  ctx.fillStyle = 'rgba(255,255,255,0.92)';
  ctx.font = '600 24px Inter, system-ui, sans-serif';
  ctx.fillText('Generated by JavaScript', 24, height - 24);
}
